package it.polimi.modaclouds.space4cloud.analysis.main;

import java.nio.file.Paths;

public class Main {
	
	private static final String DEFAULT_STATISTIC_OUTPUT = "statistics.csv";
	private static final String DEFAULT_SOLUTION_OUTPUT = "solution.csv";

	public static void main(String[] args) {
		if(args.length < 1){
			System.out.println("To few arguments, provide the location of the directory with the results");
			System.out.println("use \"help\" for instruction on input arguments");			
			return;
		}		
		
		if(args[0].equalsIgnoreCase("help")){
			printHelp();
			return;
		}
		Analyzer analyzer = new Analyzer();		
		analyzer.setBaseDir(args[0]);
		if(args.length < 2){
			System.out.println("Using default output file for statistics: "+DEFAULT_STATISTIC_OUTPUT);			
			analyzer.setStatisticFile(Paths.get(analyzer.getBaseDir().toAbsolutePath().toString(),DEFAULT_STATISTIC_OUTPUT).toString());
		}else{
			analyzer.setStatisticFile(args[1]);
		}
		if(args.length < 3){
			System.out.println("Using default output file for solution: "+DEFAULT_SOLUTION_OUTPUT);			
			analyzer.setSolutionFile(Paths.get(analyzer.getBaseDir().toAbsolutePath().toString(),DEFAULT_SOLUTION_OUTPUT).toString());
		}else{
			analyzer.setSolutionFile(args[2]);
		}
			
		
		int result = analyzer.aggregateResults();
		if(result == -1)
			System.out.println("An error occured while aggregating results");
		else
			System.out.println("Aggregation Comlpeated");
			
		
	}
	
	private static void printHelp(){
		System.out.println("The analyzer accepts 3 arguments.");
		System.out.println("\t1 - The base folder, this folder should contain at least one subfolder with the files generated in the \"space4cloud\" folder generated by a Space4Cloud run");
		System.out.println("\t2 [OPTIONAL] - The file on which to write the statistics about solution cost and optimization times. If no argument is provided the default file "+DEFAULT_STATISTIC_OUTPUT+" in the base dir is used");
		System.out.println("\t3 [OPTIONAL] - The file on which to write the statistics about the structure of the solution (type of machines and number of replicas). If no argument is provided the default file "+DEFAULT_SOLUTION_OUTPUT+" in the base dir is used");
	}

}
